services:
  catalog-db:
    image: postgres
    
  basket-db:
      image: postgres
  
  distributed-cache:
    image: redis

  catalog-api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket-api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:

